# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-mentions
  
# Site settings
title: "Sun"
description: > # this means to ignore newlines until "email:"
   A happy hideout of a guy who loves coding and mediating

email: hoangtusuhoaqua@yahoo.com
#blog logo
logo: "/assets/images/sun_logo.png"
# blog cover
cover: "/assets/images/blissful.jpg"

name: 'Nhật Trung'
author: 'Nhật Trung'
author_image: "/assets/images/avatar.jpeg"

paginate:	5

permalink: /:categories/:title

url: "http://eldesperado.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@eldesperado381'

#fill in disqus shortname to use disqus
disqus: nhat_trung

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/eldesperado381
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/eldesperado
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

exclude:
  - bower.json
  - s3_website.yml
  - bower_components
